import type { AppData, AppInfo } from '../types'

const defaultConversationId = 'main-chat'
const defaultConversationTimestamp = '2026-01-01T00:00:00.000Z'
const defaultSyncMeta = () => ({
  lastModified: new Date().toISOString(),
  syncEligible: true,
  syncVersion: 1,
  deviceSource: 'desktop_local' as const,
  pendingSync: false,
  localOnly: true,
})

export const createDefaultAppData = (): AppData => ({
  memory: [],
  settings: {
    localFirst: true,
    providerSettings: {
      preferredProvider: 'rule-based',
      ollamaUrl: 'http://localhost:11434',
      ollamaModel: '',
      openAiApiKey: '',
      geminiApiKey: '',
      claudeApiKey: '',
    },
    uiPreferences: {
      themePreference: 'godzilla',
      sidebarCollapsed: false,
      lastView: 'dashboard',
      memorySearch: '',
      memoryCategoryFilter: 'all',
      memoryPinnedOnly: false,
      memoryTagFilter: '',
      memoryArchivedOnly: false,
      memorySortOrder: 'newest',
      notesActiveTab: 'clean',
    },
    helperPreferences: {
      notesRememberDrafts: true,
      focusPreset: 'quick_reset',
      focusTimerMinutes: 25,
      familyTemplate: 'calm_boundary',
      seniorEasyMode: false,
    },
    remoteAccess: {
      mode: 'local_only',
      tailscaleEnabled: false,
      remoteSyncPlanned: false,
      remoteApiBridgeEnabled: false,
      remoteAiRequestsEnabled: false,
      androidCompanionPlanned: true,
      browserAccessEnabled: false,
      browserHostMode: 'localhost_only',
      browserBindHost: '127.0.0.1',
      browserPort: 4173,
      localAccessPin: '',
      trustedNetworkLabel: 'Home LAN / Tailscale private mesh',
    },
    androidBridge: {
      enabled: false,
      localBridgePort: 43117,
      bridgeMode: 'off',
      pairingCode: '',
      allowedDevices: [],
      pairedDevices: [],
      lastSeenAt: null,
      syncPreviewLastCheckedAt: null,
      syncPairingPlaceholder: 'Prepared for future local pairing. Not active yet.',
    },
    sync: {
      allowLanSyncPrep: true,
      allowLocalhostBridgePrep: true,
      allowTailscaleSyncPrep: false,
      trustedDevicePlaceholders: [],
      pairingRequest: {
        requestId: '',
        status: 'idle',
        requestedAt: null,
        expiresAt: null,
      },
      lastSyncSessionId: null,
    },
    notifications: {
      enabled: false,
      desktopNotificationPrep: true,
      browserNotificationFallback: 'manual_prompt_only',
      reminders: [],
    },
    release: {
      buildChannel: 'development',
      releaseType: 'dev_snapshot',
      environmentStatus: 'browser_fallback',
      packagingPrep: {
        installerReadyPlaceholder: false,
        portableModeReadyPlaceholder: false,
        optionalUpdaterPlanned: true,
      },
    },
    security: {
      encryptionPrep: {
        encryptedLocalExportPlanned: true,
        encryptedSyncPayloadPlanned: true,
        encryptedMemoryCategoriesPlanned: true,
        securePairingPlanned: true,
      },
      partitioning: {
        healthSensitiveCategories: ['health_context', 'blood_sugar', 'medicine', 'symptom'],
        familySeniorSensitiveCategories: ['safe_note', 'user_preference'],
        localAiSafeOnlyVisibility: false,
        exportSafeOnlyVisibility: false,
        syncEligibleOnlyVisibility: false,
      },
      localOnlyIndicatorsEnabled: true,
    },
    tester: {
      feedback: {
        testerNotes: '',
        bugReportDraft: '',
        localFeedbackQueue: [],
      },
      debugTools: {
        compactResetPrepEnabled: true,
        safeCacheClearPrepEnabled: true,
        workflowResetPrepEnabled: true,
        importExportValidationPrepEnabled: true,
      },
    },
    accessibility: {
      largerText: false,
      higherContrast: false,
      keyboardNavigationPrep: true,
      simplifiedWording: false,
    },
    androidEcosystem: {
      sharedWorkflowSyncPrep: true,
      sharedNotesTasksSummaryPrep: true,
      sharedFocusSessionsPrep: true,
      sharedFamilySeniorSummaryPrep: true,
      aiSafeMemorySyncPreviewPrep: true,
    },
    localAi: {
      providerMode: 'rule_based',
      ollama: {
        enabled: false,
        baseUrl: 'http://localhost:11434',
        selectedModel: '',
        availableModels: [],
        lastStatus: 'unavailable',
        lastCheckedAt: null,
        errorMessage: '',
      },
      context: {
        contextMode: 'minimal',
        maxContextMessages: 6,
        allowConversationTitles: false,
        allowTaskContext: false,
        allowNotesContext: false,
        allowMemoryHighlights: false,
      },
    },
  },
  workflows: {
    notes: {
      input: '',
      cleanText: '',
      shoppingItems: [],
      taskItems: [],
      taskSearch: '',
      taskFilterStatus: 'all',
      taskFilterCategory: 'all',
      template: 'blank',
      updatedAt: null,
    },
    chat: {
      conversations: [
        {
          id: defaultConversationId,
          title: 'Main Chat',
          createdAt: defaultConversationTimestamp,
          updatedAt: defaultConversationTimestamp,
          pinned: false,
          messages: [],
        },
      ],
      activeConversationId: defaultConversationId,
    },
    dashboard: {
      collapsedSections: [],
      pinnedWidgets: ['memory', 'tasks', 'conversations'],
      quickActionIds: [
        'open_chat',
        'health_summary',
        'persistent_notes',
        'memory_review',
      ],
    },
    syncSessions: [],
    syncConflicts: [],
    routines: [
      {
        id: 'routine-morning',
        name: 'Morning Routine',
        description: 'Start the day with focus and planning steps.',
        category: 'morning_routine',
        trigger: 'manual',
        enabled: true,
        status: 'idle',
        lastRunAt: null,
        syncMeta: defaultSyncMeta(),
        steps: [
          { id: 'morning-1', title: 'Review top tasks', detail: 'Check your highest-priority tasks for today.', type: 'review' },
          { id: 'morning-2', title: 'Set first focus block', detail: 'Pick one important task to start with.', type: 'prompt' },
          { id: 'morning-3', title: 'Start 10-minute setup timer', detail: 'Clear distractions before deep work.', type: 'timer', delaySeconds: 600 },
        ],
      },
      {
        id: 'routine-focus',
        name: 'Focus Session',
        description: 'Run a clean local focus block flow.',
        category: 'focus_session',
        trigger: 'manual',
        enabled: true,
        status: 'idle',
        lastRunAt: null,
        syncMeta: defaultSyncMeta(),
        steps: [
          { id: 'focus-1', title: 'Choose one task', detail: 'Commit to a single outcome for this block.', type: 'prompt' },
          { id: 'focus-2', title: 'Silence distractions', detail: 'Mute notifications and close unrelated tabs.', type: 'checklist' },
          { id: 'focus-3', title: 'Run 25-minute timer', detail: 'Work in one uninterrupted sprint.', type: 'timer', delaySeconds: 1500 },
        ],
      },
      {
        id: 'routine-planning',
        name: 'Daily Planning',
        description: 'Prepare a realistic plan for today.',
        category: 'daily_planning',
        trigger: 'manual',
        enabled: true,
        status: 'idle',
        lastRunAt: null,
        syncMeta: defaultSyncMeta(),
        steps: [
          { id: 'planning-1', title: 'Review calendar commitments', detail: 'Identify non-negotiable time blocks.', type: 'review' },
          { id: 'planning-2', title: 'Pick top 3 outcomes', detail: 'Choose what must get done today.', type: 'prompt' },
          { id: 'planning-3', title: 'Add quick buffer blocks', detail: 'Leave recovery space between major tasks.', type: 'checklist' },
        ],
      },
      {
        id: 'routine-winddown',
        name: 'Wind Down',
        description: 'Close the day and reduce carry-over stress.',
        category: 'wind_down',
        trigger: 'manual',
        enabled: true,
        status: 'idle',
        lastRunAt: null,
        syncMeta: defaultSyncMeta(),
        steps: [
          { id: 'winddown-1', title: 'Capture unfinished items', detail: 'Move loose tasks into tomorrow.', type: 'review' },
          { id: 'winddown-2', title: 'Clear quick inbox notes', detail: 'Summarize or archive rough notes.', type: 'checklist' },
          { id: 'winddown-3', title: 'Set tomorrow first task', detail: 'Define one clear starting action.', type: 'prompt' },
        ],
      },
      {
        id: 'routine-notes',
        name: 'Notes Cleanup',
        description: 'Review and clean notes workflow output.',
        category: 'notes_cleanup',
        trigger: 'manual',
        enabled: true,
        status: 'idle',
        lastRunAt: null,
        syncMeta: defaultSyncMeta(),
        steps: [
          { id: 'notes-1', title: 'Run notes helper', detail: 'Clean raw notes into structured sections.', type: 'review' },
          { id: 'notes-2', title: 'Convert items to tasks', detail: 'Promote action lines into tracked tasks.', type: 'checklist' },
          { id: 'notes-3', title: 'Save key highlights', detail: 'Store important points as safe notes.', type: 'prompt' },
        ],
      },
    ],
    reminders: [],
    routineRuntime: {
      activeRoutineId: null,
      status: 'idle',
      message: 'No workflow run yet.',
      updatedAt: null,
    },
    activityLog: [],
  },
})

export const defaultAppInfo: AppInfo = {
  appName: 'KCxModeAI',
  appVersion: '0.0.0',
  dataFilePath: 'browser-local-storage',
  dataDirectoryPath: 'browser-local-storage',
  isPackaged: false,
  platform: 'browser',
  electronVersion: 'n/a',
  chromeVersion: 'n/a',
  nodeVersion: 'n/a',
  buildChannel: 'development',
  releaseType: 'dev_snapshot',
  environmentStatus: 'browser_fallback',
  buildCommit: 'local-dev',
  packagingTarget: 'desktop_dev',
}
