import React from "react";
import { ForgeRegionMeta, ForgeSystemMeta, ValhallaFocusMode } from "./ForgeCanvas";

type SystemInspectorProps = {
  selectedSystem: ForgeSystemMeta | null;
  selectedRegion: ForgeRegionMeta | null;
  operationalOverlay: boolean;
  setOperationalOverlay: (v: boolean) => void;
  focusMode: ValhallaFocusMode;
  setFocusMode: (v: ValhallaFocusMode) => void;
  devLogs: Array<{ id: string; timestamp: string; message: string }>;
  actionResult: { title: string; message: string } | null;
  onClearLogs: () => void;
  onEnterChamber: () => void;
  onActionClick: (action: string) => void;
};

const actions = ["Open System", "Inspect Structure", "View Connections", "Open Runtime Layer", "Enter Region", "Access Node", "Synchronize", "View Activity"];
const focusModes: ValhallaFocusMode[] = ["infrastructure", "synchronization", "region", "containment", "runtime"];
const timeline = ["Runtime Nexus completed a low-pressure sync pass.", "Cortex pressure fluctuation was dampened at containment.", "Creation Forge stabilized its heat envelope.", "Memory Vault retained a quiet trace interval.", "AI Systems returned to guarded throughput."];

export function SystemInspector({ selectedSystem, selectedRegion, operationalOverlay, setOperationalOverlay, focusMode, setFocusMode, devLogs, actionResult, onClearLogs, onEnterChamber, onActionClick }: SystemInspectorProps) {
  const [logsOpen, setLogsOpen] = React.useState(false);
  if (!selectedSystem && !selectedRegion) {
    return <aside className="valhalla-inspector"><h2>No Focus Selected</h2><div className="inspector-controls"><label><input type="checkbox" checked={operationalOverlay} onChange={(e) => setOperationalOverlay(e.target.checked)} /> Operational View</label></div><div className="inspector-modes">{focusModes.map((m) => <button key={m} className={focusMode === m ? "mode-btn active" : "mode-btn"} onClick={() => setFocusMode(m)}>{m}</button>)}</div>{actionResult && <div className="inspector-action-result"><p className="inspector-action-title">{actionResult.title}</p><p>{actionResult.message}</p></div>}<div className="inspector-placeholder"><p>Select a system or forge sector to inspect its structure.</p></div><section className="dev-log-panel"><div className="dev-log-header"><h3>Dev Logs</h3><div className="dev-log-actions"><button type="button" onClick={() => setLogsOpen((v) => !v)}>{logsOpen ? "Collapse" : "Expand"}</button><button type="button" onClick={onClearLogs}>Clear Logs</button></div></div>{logsOpen && <div className="dev-log-list">{devLogs.length === 0 ? <p className="dev-log-empty">No interaction traces yet.</p> : devLogs.map((entry) => <p key={entry.id}><span>{new Date(entry.timestamp).toLocaleTimeString()}</span>{entry.message}</p>)}</div>}</section></aside>;
  }

  if (selectedRegion) {
    return <aside className="valhalla-inspector"><h2>{selectedRegion.name}</h2><div className="inspector-controls"><label><input type="checkbox" checked={operationalOverlay} onChange={(e) => setOperationalOverlay(e.target.checked)} /> Operational View</label></div><div className="inspector-modes">{focusModes.map((m) => <button key={m} className={focusMode === m ? "mode-btn active" : "mode-btn"} onClick={() => setFocusMode(m)}>{m}</button>)}</div>{actionResult && <div className="inspector-action-result"><p className="inspector-action-title">{actionResult.title}</p><p>{actionResult.message}</p></div>}<div className="inspector-meta"><p><strong>Operational Role:</strong> {selectedRegion.role}</p><p><strong>Sync Health:</strong> {selectedRegion.sync}</p><p><strong>Active System Count:</strong> {selectedRegion.systems}</p><p><strong>Pressure Level:</strong> {selectedRegion.name === "Cortex Core" ? "Elevated" : "Controlled"}</p><p><strong>Strategic Weight:</strong> {selectedRegion.name === "Creation Forge" || selectedRegion.name === "Cortex Core" ? "Critical" : "High"}</p><p><strong>Relationships:</strong> Regional pathways remain coherent.</p><p><strong>Atmosphere:</strong> {selectedRegion.atmosphere}</p><p><strong>Summary:</strong> {selectedRegion.summary}</p><p className="inspector-lore">{selectedRegion.lore}</p></div><div className="inspector-timeline">{timeline.slice(0, 3).map((t) => <p key={t}>{t}</p>)}</div><section className="dev-log-panel"><div className="dev-log-header"><h3>Dev Logs</h3><div className="dev-log-actions"><button type="button" onClick={() => setLogsOpen((v) => !v)}>{logsOpen ? "Collapse" : "Expand"}</button><button type="button" onClick={onClearLogs}>Clear Logs</button></div></div>{logsOpen && <div className="dev-log-list">{devLogs.length === 0 ? <p className="dev-log-empty">No interaction traces yet.</p> : devLogs.map((entry) => <p key={entry.id}><span>{new Date(entry.timestamp).toLocaleTimeString()}</span>{entry.message}</p>)}</div>}</section><div className="inspector-actions">{actions.map((a) => <button key={a} type="button" onClick={() => onActionClick(a)}>{a}</button>)}</div></aside>;
  }

  return <aside className="valhalla-inspector"><h2>{selectedSystem!.name}</h2><div className="inspector-controls"><label><input type="checkbox" checked={operationalOverlay} onChange={(e) => setOperationalOverlay(e.target.checked)} /> Operational View</label></div><div className="inspector-modes">{focusModes.map((m) => <button key={m} className={focusMode === m ? "mode-btn active" : "mode-btn"} onClick={() => setFocusMode(m)}>{m}</button>)}</div>{actionResult && <div className="inspector-action-result"><p className="inspector-action-title">{actionResult.title}</p><p>{actionResult.message}</p></div>}<div className="inspector-badges"><span className="badge">{selectedSystem!.systemClass}</span><span className="badge">{selectedSystem!.region}</span><span className="badge">{selectedSystem!.state}</span></div><div className="inspector-meta"><p><strong>Classification:</strong> {selectedSystem!.classification}</p><p><strong>Region:</strong> {selectedSystem!.region}</p><p><strong>State:</strong> {selectedSystem!.state}</p><p><strong>Sync Stability:</strong> {selectedSystem!.syncLevel}</p><p><strong>Throughput:</strong> {selectedSystem!.metrics}</p><p><strong>Load:</strong> {selectedSystem!.id === "cortex" ? "Restricted" : "Nominal"}</p><p><strong>Coherence:</strong> {selectedSystem!.region === "Cortex Core" ? "Suppressed" : "Stable"}</p><p><strong>Containment:</strong> {selectedSystem!.containmentLevel}</p><p><strong>Resonance:</strong> {selectedSystem!.state === "synchronizing" ? "Rising" : "Calm"}</p><p><strong>Architecture Notes:</strong> {selectedSystem!.notes}</p><p className="inspector-lore">{selectedSystem!.lore}</p>{selectedSystem!.id === "cortex" && <><p><strong>Status:</strong> Contained</p><p><strong>Runtime:</strong> Frontend shell only</p><p><strong>Permission:</strong> Read-only</p><p><strong>Bridge:</strong> Not connected</p><p><strong>Activation:</strong> Dormant</p></>}</div><button type="button" className="enter-chamber-btn" onClick={onEnterChamber}>Enter Chamber</button><div className="inspector-timeline">{timeline.map((t) => <p key={t}>{t}</p>)}</div><section className="dev-log-panel"><div className="dev-log-header"><h3>Dev Logs</h3><div className="dev-log-actions"><button type="button" onClick={() => setLogsOpen((v) => !v)}>{logsOpen ? "Collapse" : "Expand"}</button><button type="button" onClick={onClearLogs}>Clear Logs</button></div></div>{logsOpen && <div className="dev-log-list">{devLogs.length === 0 ? <p className="dev-log-empty">No interaction traces yet.</p> : devLogs.map((entry) => <p key={entry.id}><span>{new Date(entry.timestamp).toLocaleTimeString()}</span>{entry.message}</p>)}</div>}</section><div className="inspector-actions">{actions.map((a) => <button key={a} type="button" onClick={() => onActionClick(a)}>{a}</button>)}</div></aside>;
}
